### ISSUE TITLE
Initial Setup Customisation

### ISSUE THREAD

**Issue by andreamaestri** [andreamaestri/Clarity-Canvas#5]
**As a** new user
**I want** to be prompted with an initial setup screen
**So that** I can quickly customise my workspace with options like font size, mode selection, and colour scheme.

**Type:** Feature
**Priority:** Must Have

**Acceptance Criteria:**
- [x] Initial setup screen is displayed upon first login.
- [x] Options include font size, mode selection, and colour scheme.
- [x] Changes are saved and applied immediately.

**Comment by mariaciceri** [comment]
No font selection as we shouldn't offer this feature. Initial widgets, color, name and mode are present in the popup window.

**Comment by mariaciceri** [comment]
Done creating the popup for initial choices.
